app/routes.php
<?php


Route::get('/', function() {
   return Redirect::to('/movies');
});


Route::get('/login', 'AuthController@login');
Route::post('/login', 'AuthController@loginPost');


Route::resource('genres', 'GenresController');

Route::resource('movies', 'MoviesController');
Route::get('movies/{id}/actors', 'MoviesController@actors');

Route::resource('actors', 'ActorsController');
Route::get('actors/{id}/movies', 'ActorsController@movies');

Route::resource('users', 'UsersController');

Route::resource('directors', 'DirectorsController');

app/controllers/MoviesController.php
<?php

class MoviesController extends BaseController {

	/**
	 * Movie Repository
	 *
	 * @var Movie
	 */
	protected $movie;

	public function __construct(Movie $movie)
	{
		$this->movie = $movie;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$movies = $this->movie->all();

		return View::make('movies.index', compact('movies'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('movies.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Movie::$rules);

		if ($validation->passes())
		{
			$this->movie->create($input);

			return Redirect::route('movies.index');
		}

		return Redirect::route('movies.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$movie = $this->movie->findOrFail($id);

		return View::make('movies.show', compact('movie'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$movie = $this->movie->find($id);

		if (is_null($movie))
		{
			return Redirect::route('movies.index');
		}

		return View::make('movies.edit', compact('movie'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Movie::$rules);

		if ($validation->passes())
		{
			$movie = $this->movie->find($id);
			$movie->update($input);

			return Redirect::route('movies.show', $id);
		}

		return Redirect::route('movies.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->movie->find($id)->delete();

		return Redirect::route('movies.index');
	}

}

app/views/movies/create.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Create Movie</h1>

{{ Form::open(array('route' => 'movies.store')) }}
	<ul>
        <li>
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title') }}
        </li>

        <li>
            {{ Form::label('director_id', 'Director:') }}
            {{ Form::select('director_id', Director::all()->lists('name', 'id')) }}
        </li>

        <li>
            {{ Form::label('genre_id', 'Genre:') }}
            {{ Form::select('genre_id', Genre::all()->lists('genre', 'id')) }}
        </li>

        <li>
            {{ Form::label('actor_id', 'Main Actor:') }}
            {{ Form::select('actor_id', Actor::all()->lists('name', 'id')) }}
        </li>

        <li>
            {{ Form::label('release', 'Release Date:') }}
            {{ Form::text('release') }}
        </li>

        <li>
            {{ Form::label('synopsis', 'Synopsis:') }}
            {{ Form::textarea('synopsis') }}
        </li>

        <li>
            {{ Form::label('poster_url', 'Poster Link:') }}
            {{ Form::text('poster_url') }}
        </li>

		<li>
			{{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/movies/edit.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Edit Movie</h1>
{{ Form::model($movie, array('method' => 'PATCH', 'route' => array('movies.update', $movie->id))) }}
	<ul>
        <li>
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title') }}
        </li>

        <li>
            {{ Form::label('director_id', 'Director:') }}
            {{ Form::select('director_id', Director::all()->lists('name', 'id')) }}
        </li>

        <li>
            {{ Form::label('genre_id', 'Genre:') }}
            {{ Form::select('genre_id', Genre::all()->lists('genre', 'id')) }}
        </li>

        <li>
            {{ Form::label('actor_id', 'Main Actor:') }}
            {{ Form::select('actor_id', Actor::all()->lists('name', 'id')) }}
        </li>

        <li>
            {{ Form::label('release', 'Release Date:') }}
            {{ Form::text('release') }}
        </li>

        <li>
            {{ Form::label('synopsis', 'Synopsis:') }}
            {{ Form::textarea('synopsis') }}
        </li>

        <li>
            {{ Form::label('poster_url', 'Poster Link:') }}
            {{ Form::text('poster_url') }}
        </li>

		<li>
			{{ Form::submit('Update', array('class' => 'btn btn-info')) }}
			{{ link_to_route('movies.show', 'Cancel', $movie->id, array('class' => 'btn')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/movies/index.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>All Movies</h1>

<p>{{ link_to_route('movies.create', 'Add new movie') }}</p>

@if ($movies->count())
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Title</th>
				<th>Director</th>
				<th>Genre</th>
				<th>Main Actor</th>
				<th>Release</th>
				<th>Synopsis</th>
				<th>Poster</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($movies as $movie)
				<tr>
					<td>{{{ $movie->title }}}</td>
                    <td>
                        @if($movie->director)
                        {{ link_to_route('directors.show', $movie->director->name, array($movie->director->id)) }}
                        @endif
                    </td>
                    <td>
                        @if($movie->genre)
                        {{ link_to_route('genres.show', $movie->genre->genre, array($movie->genre->id)) }}
                        @endif
                    </td>
                    <td>
                        @if($movie->actor)
                        {{ link_to_route('actors.show', $movie->actor->name, array($movie->actor->id)) }}
                        @endif
                    </td>
                    <td>{{{ $movie->release }}}</td>
					<td>{{{ $movie->synopsis }}}</td>
                    <td><img width="200" src="{{{ $movie->poster_url }}}"></td>
                    <td>{{ link_to_route('movies.edit', 'Edit', array($movie->id), array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('movies.destroy', $movie->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no movies
@endif

@stop

app/views/movies/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show Movie</h1>

<p>{{ link_to_route('movies.index', 'Return to all movies') }}</p>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			    <th>Title</th>
				<th>Director</th>
				<th>Genre</th>
				<th>Main Actor</th>
				<th>Release Date</th>
				<th>Synopsis</th>
				<th>Poster</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $movie->title }}}</td>
            <td>
                @if($movie->director)
                {{ link_to_route('directors.show', $movie->director->name, array($movie->director->id)) }}
                @endif
            </td>
            <td>
                @if($movie->genre)
                {{ link_to_route('genres.show', $movie->genre->genre, array($movie->genre->id)) }}
                @endif
            </td>
            <td>
                @if($movie->actor)
                {{ link_to_route('actors.show', $movie->actor->name, array($movie->actor->id)) }}
                @endif
            </td>
            <td>{{{ $movie->release }}}</td>
			<td>{{{ $movie->synopsis }}}</td>
			<td><img width="200" src="{{{ $movie->poster_url }}}"></td>
            <td>{{ link_to_route('movies.edit', 'Edit', array($movie->id), array('class' => 'btn btn-info')) }}</td>
            <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('movies.destroy', $movie->id))) }}
                {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
		</tr>
	</tbody>
</table>

@stop