app/routes.php
<?php


Route::get('/', function() {
   return Redirect::to('/movies');
});


Route::get('/login', 'AuthController@login');
Route::post('/login', 'AuthController@loginPost');


Route::resource('genres', 'GenresController');

Route::resource('movies', 'MoviesController');
Route::get('movies/{id}/actors', 'MoviesController@actors');

Route::resource('actors', 'ActorsController');
Route::get('actors/{id}/movies', 'ActorsController@movies');

Route::resource('users', 'UsersController');

Route::resource('directors', 'DirectorsController');

app/models/Director.php
<?php

class Director extends Eloquent {
	protected $guarded = array();

	public static $rules = array(
		'name' => 'required',
		'country' => 'required'
	);

    public function movies()
    {
        return $this->hasMany('Movie');
    }
}

app/controllers/DirectorsController.php
<?php

class DirectorsController extends BaseController {

	/**
	 * Director Repository
	 *
	 * @var Director
	 */
	protected $director;

	public function __construct(Director $director)
	{
		$this->director = $director;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$directors = $this->director->all();

		return View::make('directors.index', compact('directors'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('directors.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Director::$rules);

		if ($validation->passes())
		{
			$this->director->create($input);

			return Redirect::route('directors.index');
		}

		return Redirect::route('directors.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$director = $this->director->findOrFail($id);

		return View::make('directors.show', compact('director'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$director = $this->director->find($id);

		if (is_null($director))
		{
			return Redirect::route('directors.index');
		}

		return View::make('directors.edit', compact('director'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Director::$rules);

		if ($validation->passes())
		{
			$director = $this->director->find($id);
			$director->update($input);

			return Redirect::route('directors.show', $id);
		}

		return Redirect::route('directors.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->director->find($id)->delete();

		return Redirect::route('directors.index');
	}

}

app/views/directors/create.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Create Director</h1>

{{ Form::open(array('route' => 'directors.store')) }}
	<ul>
        <li>
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        </li>

        <li>
            {{ Form::label('country', 'Country:') }}
            {{ Form::text('country') }}
        </li>

		<li>
			{{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/directors/edit.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Edit Director</h1>
{{ Form::model($director, array('method' => 'PATCH', 'route' => array('directors.update', $director->id))) }}
	<ul>
        <li>
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        </li>

        <li>
            {{ Form::label('country', 'Country:') }}
            {{ Form::text('country') }}
        </li>

		<li>
			{{ Form::submit('Update', array('class' => 'btn btn-info')) }}
			{{ link_to_route('directors.show', 'Cancel', $director->id, array('class' => 'btn')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/directors/index.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>All Directors</h1>

<p>{{ link_to_route('directors.create', 'Add new director') }}</p>

@if ($directors->count())
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Country</th>
                <th>Movies</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($directors as $director)
				<tr>
					<td>{{{ $director->name }}}</td>
					<td>{{{ $director->country }}}</td>
                    <td>
                        <ul>
                            @foreach($director->movies as $movie)
                            <li>{{ link_to_route('movies.show', $movie->title, array($movie->id)) }}</li>
                            @endforeach
                            <ul>
                    </td>
                    <td>{{ link_to_route('directors.edit', 'Edit', array($director->id), array('class' => 'btn btn-info')) }}</td>

                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('directors.destroy', $director->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no directors
@endif

@stop

app/views/directors/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show Director</h1>

<p>{{ link_to_route('directors.index', 'Return to all directors') }}</p>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Name</th>
				<th>Country</th>
            <th>Movies</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $director->name }}}</td>
			<td>{{{ $director->country }}}</td>
            <td>
                <ul>
                    @foreach($director->movies as $movie)
                    <li>{{ link_to_route('movies.show', $movie->title, array($movie->id)) }}</li>
                    @endforeach
                    <ul>
            </td>
            <td>{{ link_to_route('directors.edit', 'Edit', array($director->id), array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('directors.destroy', $director->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
		</tr>
	</tbody>
</table>

@stop